import { makeStyles, gradientText } from '@utils/styles';

export const useStyles = makeStyles(({ breakpoints }) => ({
  root: {
    position: 'relative',
    maxWidth: 1440,
    margin: '0 auto',
  },
  bgHolder: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    overflow: 'hidden',
    [breakpoints.down('lg')]: {
      overflow: 'visible',
    },
  },
  bg: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: '50%',
    width: 1440,
    transform: 'translateX(-50%)',
    backgroundColor: '#F7FAFF',
    backgroundImage: 'linear-gradient(99.5deg, #F7FAFF 0.67%, #DEE6F1 98.71%)',
    borderRadius: 10,
    [breakpoints.down('xl')]: {
      width: '95vw',
    },
  },
  imageHolder: {
    display: 'block',
    fontSize: 0,
    margin: '-10px -35px -15px 40px',
    [breakpoints.down('lg')]: {
      transform: 'scale(0.6)',
      width: '45%',
      margin: 'auto',
    },
    [breakpoints.down('sm')]: {
      display: 'none',
    },
  },
  container: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  content: {
    flex: 1,
    padding: '2.5rem 0.5rem',
    fontSize: '1rem',
  },
  button: {
    display: 'inline-flex',
    alignItems: 'stretch',
    borderRadius: 10,
    height: 50,
    width: '100%',
    boxShadow: '0px 10px 35px rgba(0, 0, 0, 0.15)',
    color: '#fff',
    fontWeight: 600,
    fontSize: 16,
    textTransform: 'uppercase',
    [breakpoints.up('lg')]: {
      width: 'auto',
    },
    [breakpoints.down('md')]: {
      fontSize: '0.875rem',
    },
  },
  buttonCaptionHolder: {
    flex: 1,
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0 50px',
    border: '1px solid #4E446A',
    backgroundColor: '#4E4568',
    backgroundImage: 'linear-gradient(180deg, #594B81 0%, #150D1C 100%)',
    borderRadius: '10px 0 0 10px',
    letterSpacing: '0.03em',
    [breakpoints.down('md')]: {
      padding: '0 1rem',
    },
  },
  buttonCaption: {
    ...gradientText('#FFFAEA, #F4CA93'),
  },
  buttonArrowHolder: {
    position: 'absolute',
    left: '100%',
    top: -1,
    bottom: -1,
    width: 14,
    marginLeft: -1,
    overflow: 'hidden',
  },
  buttonArrow: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    transform: 'scale(0.5, 1)',
    transformOrigin: 'left center',
    '&:before': {
      position: 'absolute',
      top: '50%',
      left: '50%',
      width: 38,
      height: 38,
      borderRadius: '0 6px 0 0',
      transform: 'translate(-50%, -50%) rotate(45deg)',
      backgroundColor: '#4E4568',
      backgroundImage: 'linear-gradient(135deg, #594B81 0%, #150D1C 100%)',
      content: `''`,
    },
  },
  buttonBonus: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '0px 20px 0px 25px',
    borderRadius: '0 10px 10px 0',
    backgroundColor: '#E33355',
    backgroundImage: 'linear-gradient(180deg, #E33355 0%, #AF2D46 100%)',
    fontSize: 0,
  },
  bonusIcon: {
    width: '1em',
    lineHeight: 1,
    fontSize: 20,
    color: '#FFEFD9',
    ...gradientText('#FFEFD9, #EBBA79'),
  },
}));
