import { makeStyles, gradientText } from '@utils/styles';

// images
import MapPng from './images/map.png';
import PinSvg from './images/pin.svg';

export const useStyles = makeStyles(({ breakpoints }) => ({
  '@keyframes blink': {
    '0%, 100%': {
      opacity: 1,
    },
    '50%': {
      opacity: 0.1,
    },
  },
  root: {
    position: 'relative',
    padding: '30px 0 60px',
    backgroundColor: '#1B0621',
    backgroundImage: 'linear-gradient(180deg, #1B0621 0%, #0C010F 54.17%, #0f0212 100%)',
    textAlign: 'center',
    color: '#fff',
    '&:before': {
      position: 'absolute',
      top: -1,
      left: '50%',
      border: '24px solid transparent',
      borderBottom: 'none',
      borderTop: '15px solid #fff',
      transform: 'translateX(-50%)',
      pointerEvents: 'none',
      content: `''`,
    },
  },
  content: {
    position: 'relative',
  },
  title: {
    fontWeight: 'bold',
    fontSize: 150,
    lineHeight: 1,
    margin: 0,
    letterSpacing: '-0.05em',
    textTransform: 'uppercase',
    color: '#310B3C',
    ...gradientText('#310B3C, #1B0620'),
  },
  text: {
    margin: '-50px 0 0 0',
    fontWeight: 'bold',
    fontSize: 50,
    lineHeight: 1,
  },
  countText: {
    position: 'relative',
    display: 'inline-flex',
    margin: '0 32px',
    fontSize: 100,
    letterSpacing: '-0.07em',
    color: 'transparent',
    textShadow: '0px 5px 0px #685132',
    whiteSpace: 'nowrap',
    '&:after': {
      position: 'absolute',
      top: 0,
      left: 0,
      bottom: 0,
      paddingRight: 5,
      color: '#F8DAB1',
      textShadow: 'none',
      content: 'attr(title)',
      ...gradientText('#F8DAB1, #BD9662'),
    },
  },
  redText: {
    color: '#D41841',
  },
  whiteText: {
    color: '#fff',
  },
  bottom: {
    position: 'relative',
  },
  bottomText: {
    maxWidth: 600,
    margin: '0 auto',
    fontSize: 14,
    color: '#676982',
    '& > p': {
      margin: '0',
      '& span': {
        color: '#D41841',
      },
    },
    [breakpoints.up('md')]: {
      fontSize: 18,
    },
    [breakpoints.up('lg')]: {
      fontSize: 22,
    },
  },
  map: {
    position: 'relative',
    minHeight: 460,
    margin: '60px 0 -60px',
    backgroundImage: `url(${MapPng})`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'top center',
    '&:before': {
      position: 'absolute',
      top: 0,
      right: 0,
      left: 0,
      bottom: 0,
      backgroundColor: 'transparent',
      backgroundImage: 'radial-gradient(center, ellipse closest-side, #C957E8 0%, transparent 100%)',
      opacity: 0.15,
      pointerEvents: 'none',
      content: `''`,
    },
  },
  mapPin: {
    position: 'absolute',
    top: '50%',
    left: '50%',
  },
  mapPinInner: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    display: 'inline-flex',
    fontWeight: 'bold',
    textAlign: 'left',
    fontSize: 20,
    lineHeight: 1,
    backgroundImage: `url(${PinSvg})`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'left top',
    minHeight: 56,
  },
  mapIcon: {
    paddingTop: 6,
    width: 37,
    marginRight: 10,
    textAlign: 'center',
    fontSize: 0,
  },
  mapText: {
    whiteSpace: 'nowrap',
    lineHeight: 1.2,
    color: '#fff',
    ...gradientText('#fff, #BD9662'),
  },
  stars: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: 'none',
    overflow: 'hidden',
  },
  star: {
    position: 'absolute',
    animation: '$blink 3s ease-in infinite',
    '& > span': {
      position: 'absolute',
      width: '100%',
      height: '100%',
      borderRadius: '50%',
      backgroundColor: '#fff',
      content: `''`,
    },
  },
  flash: {
    position: 'absolute',
    left: '50%',
    opacity: 0.7,
    '&:before': {
      position: 'absolute',
      left: '50%',
      top: '50%',
      width: 2,
      height: 2,
      borderRadius: '50%',
      backgroundColor: '#fff',
      transform: 'translate(-50%, -50%)',
      content: `''`,
    },
  },
  flashPurple: {
    bottom: 20,
    width: 240,
    height: 240,
    marginLeft: -120,
    transform: 'translateX(-760px)',
    backgroundColor: 'transparent',
    backgroundImage: 'radial-gradient(center, ellipse closest-side, #3E0851 0%, transparent 100%)',
  },
  flashBlue: {
    top: 20,
    width: 220,
    height: 220,
    marginLeft: -110,
    transform: 'translateX(740px)',
    backgroundColor: 'transparent',
    backgroundImage: 'radial-gradient(center, ellipse closest-side, #083F51 0%, transparent 100%)',
  },
  blink: {
    position: 'absolute',
    left: '50%',
    opacity: 0.7,
    '&:before': {
      position: 'absolute',
      left: '50%',
      top: '50%',
      width: 4,
      height: 4,
      borderRadius: '50%',
      backgroundColor: '#fff',
      transform: 'translate(-50%, -50%)',
      content: `''`,
    },
  },
  blinkRed: {
    top: 250,
    width: 80,
    height: 80,
    marginLeft: -40,
    transform: 'translateX(600px)',
    backgroundColor: 'transparent',
    background: `
      linear-gradient(to bottom right, #E33355, transparent 40%) bottom right,
      linear-gradient(to bottom left, #E33355, transparent 40%) bottom left,
      linear-gradient(to top left, #E33355, transparent 40%) top left,
      linear-gradient(to top right, #E33355, transparent 40%) top right`,
    backgroundSize: '50% 50%',
    backgroundRepeat: 'no-repeat',
    opacity: 0.6,
  },
  blinkBlue: {
    top: 350,
    width: 70,
    height: 70,
    marginLeft: -35,
    transform: 'translateX(-700px)',
    backgroundColor: 'transparent',
    background: `
      linear-gradient(to bottom right, #33B9E3, transparent 40%) bottom right,
      linear-gradient(to bottom left, #33B9E3, transparent 40%) bottom left,
      linear-gradient(to top left, #33B9E3, transparent 40%) top left,
      linear-gradient(to top right, #33B9E3, transparent 40%) top right`,
    backgroundSize: '50% 50%',
    backgroundRepeat: 'no-repeat',
    opacity: 0.5,
  },
  logo: {
    maxWidth: '40%',
  },
}));
